### ISSUE TITLE
Implement END_OPTION in GameControl

### ISSUE THREAD

**Issue by DBrueberg** [DBrueberg/ZombieWar#14]
When the EndGameControl case #7 is complete. Implement it into the GameControl displayMenu() method. The code should just need to be uncommented if EndGameControl has a static method called endGame() that returns false.
![endOptionFinish](https://user-images.githubusercontent.com/72808143/143958470-877c4b7b-371b-4231-b45a-aa689852dfc6.gif)

**Comment by dietschc** [comment]
This was handled in https://github.com/DBrueberg/ZombieWar/issues/7,

Closing duplicate issue.
