### ISSUE TITLE
Implement PrintReportControl in PlayMatchControl

### ISSUE THREAD

**Issue by DBrueberg** [DBrueberg/ZombieWar#15]
Uncomment and test that the Report is properly printed according to version 1 standards of "It seems 6 have made it to saftey." If there is a printReport() method in PrintReportControl case #that prints this, then all that should be needed is to uncomment the createPrintReportControl() method in PlayMatchControl.
![printReportInPlayMatch](https://user-images.githubusercontent.com/72808143/143958950-894870d9-6a28-4bc2-8f32-fb8d1d16c5ea.gif)

**Comment by dietschc** [comment]
This has also been implemented in another PR. https://github.com/DBrueberg/ZombieWar/issues/3

I am closing this duplicate issue for now.
