### ISSUE TITLE
PrintReportControl and Report

### ISSUE THREAD

**Issue by noko12312** [DBrueberg/ZombieWar#3]
Create _PrintReportControl_ and _Report_ classes. The _PrintReportControl_ class will receive data on the starting number of survivors and zombies as well as the amount of survivors left from the _PlayMatchControl_ class after the _Match_ ends . It will then create a _Report_ instance that will print the information to the user similar to the example output shown below:

Please pull right off of version1 to start.

Release 1.0's sample run:
It seems 6 have made it to safety.

Flow of operations can be seen in the PlayMatch Sequence Diagram. However, a Class Diagram showing methods and instance variables may be helpful to implement.
![Play Match Sequence Diagram](https://user-images.githubusercontent.com/42224565/143731597-7089d1e4-46f1-4cda-9a8f-36b91cb7b2da.JPG)

PlayMatchControl calls PrintReportControl which creates a PrintReportControl object which should create a Report. PrintReportControl will will print the report using a public method called printReport() as shown from the PlayMatchControl.java file below

![createPrintReportControlInPlayMatchControl](https://user-images.githubusercontent.com/72808143/143799190-a3bda198-c30a-443d-949a-9d0a6460ec8d.gif)

**Comment by dietschc** [comment]
These changes have been merged into version1.
