### ISSUE TITLE
Update existing Character.Survivor class and subclasses to use Weapon objects.

### ISSUE THREAD

**Issue by dietschc** [DBrueberg/ZombieWar#32]
After some brainstorming it was decided that Zombie's will not have access to Weapon objects at all. So Weapon function will only be added to Survivor objects.

A major functional aspect will be that the Character attack() method will be overriden in Survivor to provide for the Weapon functionality when attacking. This feature has its own issue #34 .

The new UML to reflect these changes is posted below.
![characterClassUMLv2](https://user-images.githubusercontent.com/72808143/145699172-bfc932ad-5767-45b7-b67a-4f63f4629b26.gif)

**Comment by DBrueberg** [comment]
After some brainstorming it was decided that Zombie's will not have access to Weapon objects at all. So Weapon function will only be added to Survivor objects. 

A major functional aspect will be that the Character attack() method will be overriden in Survivor to provide for the Weapon functionality when attacking. This feature has its own issue #34 .

The new UML to reflect these changes is posted below. 

![characterClassUMLv2](https://user-images.githubusercontent.com/72808143/145698977-f43ccce3-d040-458a-9401-3f097110bd81.gif)
