### ISSUE TITLE
Implement method to generate a random weapon cache that can be used by Character.Survivor subclasses.

### ISSUE THREAD

**Issue by dietschc** [DBrueberg/ZombieWar#33]
When implementing this feature a weapons cache will need to be created, then the Survivor Characters will randomly pick a Weapon from the cache. When a Weapon is selected it should be removed from the cache.

Implement this is CharacterList.java before the Survivor List is returned to the caller.

The exact instructions read as follows:
"Add weapons. The weapon cache is randomly generated. The survivors randomly picked a weapon."

**Comment by DBrueberg** [comment]
When implementing this feature a weapons cache will need to be created, then the Survivor Characters will randomly pick a Weapon from the cache. When a Weapon is selected it should be removed from the cache. 

Implement this is CharacterList.java before the Survivor List is returned to the caller.

The exact instructions read as follows: 
"Add weapons. The weapon cache is randomly generated. The survivors randomly picked a weapon."
