### ISSUE TITLE
Implement weapon damage and accuracy modifier in Survivor

### ISSUE THREAD

**Issue by dietschc** [DBrueberg/ZombieWar#34]
The Survivor Class will have to override the Character attack() method and add the functionality to attack with a Weapon if one is equipped. If a Weapon is not equipped the enemy Character will take the standard Character specific damage. If a Weapon is equipped the enemy Character will take either the full Weapon damage if the attack hits or 0 damage if the attack misses.

**Comment by DBrueberg** [comment]
The Survivor Class will have to override the Character attack() method and add the functionality to attack with a Weapon if one is equipped. If a Weapon is not equipped the enemy Character will take the standard Character specific damage. If a Weapon is equipped the enemy Character will take either the full Weapon damage if the attack hits or 0 damage if the attack misses.
