### ISSUE TITLE
Update Match to indicate the weapon used by a Survivor to kill a zombie.

### ISSUE THREAD

**Issue by dietschc** [DBrueberg/ZombieWar#35]
The sample run is similar to release 2 but it should indicate the weapon used to kill an infected.

The Weapon can be retrieved from the getWeapon() method in a Survivor object. The toString() method in a Weapon object will print out that weapons name. The exact instructions for this feature read as follows:
"The sample run is similar to release 2 but it should indicate the weapon used to kill an infected."

Possibly implement in the xAttackAllY() method in Match where the death already is printed out.

**Comment by DBrueberg** [comment]
The Weapon can be retrieved from the getWeapon() method in a Survivor object. The toString() method in a Weapon object will print out that weapons name. The exact instructions for this feature read as follows: 
"The sample run is similar to release 2 but it should indicate the weapon used to kill an infected."

Possibly implement in the xAttackAllY() method in Match where the death already is printed out.
