### ISSUE TITLE
EndGameControl

### ISSUE THREAD

**Issue by DBrueberg** [DBrueberg/ZombieWar#7]
The _EndGameControl_ will perform the actions needed before terminating a game. It will be called through the _EndOption_ found in _GameControl_. It should have a static method. 

Please pull right off of version1 to start.

![endGameSequence](https://user-images.githubusercontent.com/72808143/143782496-7e3078dd-9cf9-4716-ab70-b246e6ff73ae.gif)

**Comment by dietschc** [comment]
These changes have been merged into version1.
